// Mocks generated by Mockito 5.4.4 from annotations
// in blinqpay/test/view_models/post_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blinqpay/app/repository/interfaces/post_repository_interface.dart'
    as _i3;
import 'package:blinqpay/app/services/posts/interfaces/post_service_interface.dart'
    as _i5;
import 'package:blinqpay/models/api_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepositoryInterface extends _i1.Mock
    implements _i3.PostRepositoryInterface {
  MockPostRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<dynamic>> getPosts(
          _i5.PostServiceInterface? postService) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [postService],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getPosts,
            [postService],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<dynamic>>);
}

/// A class which mocks [PostServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostServiceInterface extends _i1.Mock
    implements _i5.PostServiceInterface {
  MockPostServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<dynamic>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getPosts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<dynamic>>);
}
