// Mocks generated by Mockito 5.4.4 from annotations
// in blinqpay/test/view_models/user_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blinqpay/app/repository/interfaces/user_repository_interface.dart'
    as _i3;
import 'package:blinqpay/app/services/users/interfaces/user_service_interface.dart'
    as _i5;
import 'package:blinqpay/models/api_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepositoryInterface extends _i1.Mock
    implements _i3.UserRepositoryInterface {
  MockUserRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<dynamic>> getUsers(
          _i5.UserServiceInterface? userService) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [userService],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<dynamic>>.value(
            _FakeApiResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUsers,
            [userService],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<dynamic>>);
}

/// A class which mocks [UserServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserServiceInterface extends _i1.Mock
    implements _i5.UserServiceInterface {
  MockUserServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
